"""add themes

Revision ID: 913ed14d47d2
Revises: ce6592345513
Create Date: 2025-06-06 21:42:42.675776

"""
from alembic import op
import sqlalchemy as sa
from models import Theme


# revision identifiers, used by Alembic.
revision = '913ed14d47d2'
down_revision = 'ce6592345513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('css_file', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint('uq_theme_name', ['name'])

    # ### end Alembic commands ###

    # 添加初始主题数据
    op.bulk_insert(
        Theme.__table__,
        [
            {
                'name': 'light',
                'description': '明亮主题，适合白天使用',
                'css_file': 'css/themes/light.css',
                'is_active': True
            },
            {
                'name': 'dark',
                'description': '暗色主题，适合夜间使用',
                'css_file': 'css/themes/dark.css',
                'is_active': False
            }
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('description')
        batch_op.drop_column('is_active')
        batch_op.drop_column('css_file')

    # ### end Alembic commands ###